  // Copyright 2019 The Swarm Authors
  // This file is part of the Swarm library.
  //
  // The Swarm library is free software: you can redistribute it and/or modify
  // it under the terms of the GNU Lesser General Public License as published by
  // the Free Software Foundation, either version 3 of the License, or
  // (at your option) any later version.
  //
  // The Swarm library is distributed in the hope that it will be useful,
  // but WITHOUT ANY WARRANTY; without even the implied warranty of
  // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  // GNU Lesser General Public License for more details.
  //
  // You should have received a copy of the GNU Lesser General Public License
  // along with the Swarm library. If not, see <http://www.gnu.org/licenses/>.
  //
  // Code generated - DO NOT EDIT.
  // This file was autogenerated with 'npm run abigen' from ethersphere/swap-swear-and-swindle and any manual changes will be lost.
  package migrations

  // MigrationsDeployedCode is the bytecode Migrations will have after deployment
  const MigrationsDeployedCode = "0x608060405234801561001057600080fd5b506004361061004c5760003560e01c80630900f01014610051578063445df0ac146100795780638da5cb5b14610093578063fdacd576146100b7575b600080fd5b6100776004803603602081101561006757600080fd5b50356001600160a01b03166100d4565b005b610081610151565b60408051918252519081900360200190f35b61009b610157565b604080516001600160a01b039092168252519081900360200190f35b610077600480360360208110156100cd57600080fd5b5035610166565b6000546001600160a01b031633141561014e576000819050806001600160a01b031663fdacd5766001546040518263ffffffff1660e01b815260040180828152602001915050600060405180830381600087803b15801561013457600080fd5b505af1158015610148573d6000803e3d6000fd5b50505050505b50565b60015481565b6000546001600160a01b031681565b6000546001600160a01b031633141561014e5760015556fea26469706673582212208d7b62b002a53d552b97d91ae9934cdb59ad725ee7a131b3fb1822090adfc93464736f6c634300060c0033"
